### ISSUE TITLE
ชื่อทีม?

### ISSUE THREAD

**Issue by ScriptBloxX** [slxyz2508/INT100-G1-03-test#1]
เราจะตั้งชื่อทีมว่าอะไรดีเพื่อนๆ

**Comment by slxyz2508** [comment]
ผมเสอนให้ตัวอักษรหน้าชื่อทุกคนมาเรียนเป็นคำ ครับผม

**Comment by KuroMimeow** [comment]
ด้ายยย

**Comment by ScriptBloxX** [comment]
MOFFET !

M-Mind
O-O
F-First
F-Fah
E-Eve
T-Ton
